// Code generated by 'yaegi extract github.com/suifengpiao14/goscript/yaegi/funcs'. DO NOT EDIT.

package yaegi

import (
	"github.com/suifengpiao14/goscript/yaegi/funcs"
	"reflect"
)

func init() {
	Symbols["github.com/suifengpiao14/goscript/yaegi/funcs/funcs"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetsetJson":     reflect.ValueOf(funcs.GetsetJson),
		"GetsetJsonByte": reflect.ValueOf(funcs.GetsetJsonByte),
	}
}
